function Prefix() {
  var gSobject = gs.init('Prefix');
  gSobject.clazz = { name: 'Prefix', simpleName: 'Prefix'};
  gSobject.clazz.superclass = { name: 'java.lang.Object', simpleName: 'Object'};
  gSobject.preVowel = null;
  gSobject.preConsonant = null;
  if (arguments.length == 1) {gs.passMapToObject(arguments[0],gSobject);};
  
  return gSobject;
 };

var Tense = {
  PRESENT : { ordinal: function() { return 0}, name: function() { return 'PRESENT' } },
  FUTURE_IMPERATIVE : { ordinal: function() { return 1}, name: function() { return 'FUTURE_IMPERATIVE' } },
  INFINITIVE : { ordinal: function() { return 2}, name: function() { return 'INFINITIVE' } },
  HABITUAL : { ordinal: function() { return 3}, name: function() { return 'HABITUAL' } },
  PLUPERFECT : { ordinal: function() { return 4}, name: function() { return 'PLUPERFECT' } },
  FUTURE_PROGRESSIVE : { ordinal: function() { return 5}, name: function() { return 'FUTURE_PROGRESSIVE' } },
  REPORTATIVE : { ordinal: function() { return 6}, name: function() { return 'REPORTATIVE' } },
  PAST : { ordinal: function() { return 7}, name: function() { return 'PAST' } },
  FUTURE : { ordinal: function() { return 8}, name: function() { return 'FUTURE' } },
  PRE_INCIPIENT : { ordinal: function() { return 9}, name: function() { return 'PRE_INCIPIENT' } },
  
}
var VerbTense = gs.map();
gs.mc(VerbTense,"put",["esdi", gs.gp(Tense,"FUTURE_PROGRESSIVE")]);
gs.mc(VerbTense,"put",["idi", gs.gp(Tense,"PRE_INCIPIENT")]);
gs.mc(VerbTense,"put",["vi", gs.gp(Tense,"FUTURE_IMPERATIVE")]);
gs.mc(VerbTense,"put",["di", gs.gp(Tense,"INFINITIVE")]);
gs.mc(VerbTense,"put",["oi", gs.gp(Tense,"HABITUAL")]);
gs.mc(VerbTense,"put",["oi", gs.gp(Tense,"PLUPERFECT")]);
gs.mc(VerbTense,"put",["ei", gs.gp(Tense,"REPORTATIVE")]);
gs.mc(VerbTense,"put",["vi", gs.gp(Tense,"PAST")]);
gs.mc(VerbTense,"put",["i", gs.gp(Tense,"FUTURE")]);
gs.mc(VerbTense,"put",["a", gs.gp(Tense,"PRESENT")]);
var VerbTenseLookup = gs.map();
gs.mc(VerbTenseLookup,"put",["FUTURE_PROGRESSIVE", "esdi"]);
gs.mc(VerbTenseLookup,"put",["PRE_INCIPIENT", "idi"]);
gs.mc(VerbTenseLookup,"put",["FUTURE_IMPERATIVE", "vi"]);
gs.mc(VerbTenseLookup,"put",["INFINITIVE", "di"]);
gs.mc(VerbTenseLookup,"put",["HABITUAL", "oi"]);
gs.mc(VerbTenseLookup,"put",["PLUPERFECT", "oi"]);
gs.mc(VerbTenseLookup,"put",["REPORTATIVE", "ei"]);
gs.mc(VerbTenseLookup,"put",["PAST", "vi"]);
gs.mc(VerbTenseLookup,"put",["FUTURE", "i"]);
gs.mc(VerbTenseLookup,"put",["PRESENT", "a"]);
var FinalEndings = gs.map();
gs.mc(FinalEndings,"put",["dv", "focus"]);
gs.mc(FinalEndings,"put",["dina", "concessiveImperative"]);
gs.mc(FinalEndings,"put",["isi", "orelse"]);
gs.mc(FinalEndings,"put",["hv", "but"]);
gs.mc(FinalEndings,"put",["na", "andWhatIf"]);
gs.mc(FinalEndings,"put",["ke", "orInterrogative"]);
gs.mc(FinalEndings,"put",["tsu", "interrogative"]);
gs.mc(FinalEndings,"put",["sgo", "interrogative2"]);
gs.mc(FinalEndings,"put",["gwu", "onlyJustStill"]);
gs.mc(FinalEndings,"put",["quu", "onlyJustStill"]);
var NonFinalEndings = gs.map();
gs.mc(NonFinalEndings,"put",["dohdan", "unintentional"]);
gs.mc(NonFinalEndings,"put",["idol", "around"]);
gs.mc(NonFinalEndings,"put",["ilo", "repetitive"]);
gs.mc(NonFinalEndings,"put",["ilos", "repetitive"]);
gs.mc(NonFinalEndings,"put",["ilots", "repetitive"]);
gs.mc(NonFinalEndings,"put",["ihl", "comeTo"]);
gs.mc(NonFinalEndings,"put",["dan", "instrumentalCausative"]);
gs.mc(NonFinalEndings,"put",["ohn", "completive"]);
gs.mc(NonFinalEndings,"put",["is", "duplicative/become"]);
gs.mc(NonFinalEndings,"put",["el", "dativeBenefactive"]);
gs.mc(NonFinalEndings,"put",["gi", "reversive"]);
gs.mc(NonFinalEndings,"put",["g", "progressive"]);
gs.mc(NonFinalEndings,"put",["e", "atIntervals"]);
gs.mc(NonFinalEndings,"put",["y", "reversive"]);
gs.mc(NonFinalEndings,"put",["e", "reversive"]);
var VowelPrefixes = gs.map();
gs.mc(VowelPrefixes,"put",["gatsiy", "SG1PL3AN"]);
gs.mc(VowelPrefixes,"put",["dogin", "DL1EXCLPL3INB"]);
gs.mc(VowelPrefixes,"put",["dugin", "DL1INCLPL3INB"]);
gs.mc(VowelPrefixes,"put",["gahiy", "SG2PL3AN"]);
gs.mc(VowelPrefixes,"put",["gegin", "PL3DL1INCL"]);
gs.mc(VowelPrefixes,"put",["gogin", "PL3DL1EXCL"]);
gs.mc(VowelPrefixes,"put",["isgiy", "PL2DL1EXCL"]);
gs.mc(VowelPrefixes,"put",["itsvy", "PL1EXCLSG2"]);
gs.mc(VowelPrefixes,"put",["daqu", "SG1PL3INB"]);
gs.mc(VowelPrefixes,"put",["dagw", "SG1PL3INB"]);
gs.mc(VowelPrefixes,"put",["desd", "DL2PL3IN"]);
gs.mc(VowelPrefixes,"put",["dosd", "DL1EXCLPL3IN"]);
gs.mc(VowelPrefixes,"put",["gesd", "PL3DL2"]);
gs.mc(VowelPrefixes,"put",["gosd", "DL1EXCLPL3AN"]);
gs.mc(VowelPrefixes,"put",["gvqu", "PL3SG1"]);
gs.mc(VowelPrefixes,"put",["gvgw", "PL3SG1"]);
gs.mc(VowelPrefixes,"put",["ogin", "DL1EXCLSG3INB"]);
gs.mc(VowelPrefixes,"put",["sdvy", "DL1EXCLDL2"]);
gs.mc(VowelPrefixes,"put",["sgin", "DL2DL1EXCL"]);
gs.mc(VowelPrefixes,"put",["tsiy", "SG1SG3AN"]);
gs.mc(VowelPrefixes,"put",["aqu", "SG1SG3INB"]);
gs.mc(VowelPrefixes,"put",["agw", "SG1SG3INB"]);
gs.mc(VowelPrefixes,"put",["dan", "PL3PL3IN"]);
gs.mc(VowelPrefixes,"put",["ded", "PL1INCLPL3IN"]);
gs.mc(VowelPrefixes,"put",["deg", "SG3PL3IN"]);
gs.mc(VowelPrefixes,"put",["deh", "SG2PL3IN"]);
gs.mc(VowelPrefixes,"put",["dets", "PL2PL3IN"]);
gs.mc(VowelPrefixes,"put",["den", "DL1INCLPL3IN"]);
gs.mc(VowelPrefixes,"put",["dog", "PL1EXCLPL3INB"]);
gs.mc(VowelPrefixes,"put",["dots", "PL1EXCLPL3IN"]);
gs.mc(VowelPrefixes,"put",["dug", "PL1INCLPL3INB"]);
gs.mc(VowelPrefixes,"put",["duts", "SG2PL3INB"]);
gs.mc(VowelPrefixes,"put",["dun", "PL3PL3INB"]);
gs.mc(VowelPrefixes,"put",["duw", "SG3PL3INB"]);
gs.mc(VowelPrefixes,"put",["esd", "DL2SG3AN"]);
gs.mc(VowelPrefixes,"put",["ged", "PL1INCLPL3AN"]);
gs.mc(VowelPrefixes,"put",["geg", "PL3PL1INCL"]);
gs.mc(VowelPrefixes,"put",["gets", "PL3PL2"]);
gs.mc(VowelPrefixes,"put",["gen", "DL1INCLPL3AN"]);
gs.mc(VowelPrefixes,"put",["gin", "DL1INCLSG3INB"]);
gs.mc(VowelPrefixes,"put",["gog", "PL3PL1EXCL"]);
gs.mc(VowelPrefixes,"put",["gots", "PL1EXCLPL3AN"]);
gs.mc(VowelPrefixes,"put",["gvy", "SG1SG2"]);
gs.mc(VowelPrefixes,"put",["hiy", "SG2SG3AN"]);
gs.mc(VowelPrefixes,"put",["osd", "DL1EXCLSG3IN"]);
gs.mc(VowelPrefixes,"put",["squ", "SG2SG1"]);
gs.mc(VowelPrefixes,"put",["sgw", "SG2SG1"]);
gs.mc(VowelPrefixes,"put",["an", "PL3SG3IN"]);
gs.mc(VowelPrefixes,"put",["ed", "PL1INCLSG3AN"]);
gs.mc(VowelPrefixes,"put",["ets", "PL2SG3AN"]);
gs.mc(VowelPrefixes,"put",["en", "DL1INCLSG3AN"]);
gs.mc(VowelPrefixes,"put",["id", "PL1INCLSG3IN"]);
gs.mc(VowelPrefixes,"put",["ig", "PL1INCLSG3INB"]);
gs.mc(VowelPrefixes,"put",["its", "PL2SG3IN"]);
gs.mc(VowelPrefixes,"put",["in", "DL1INCLSG3IN"]);
gs.mc(VowelPrefixes,"put",["og", "PL1EXCLSG3INB"]);
gs.mc(VowelPrefixes,"put",["ots", "PL1EXCLSG3IN"]);
gs.mc(VowelPrefixes,"put",["sd", "DL2SG3IN"]);
gs.mc(VowelPrefixes,"put",["un", "PL3SG3INB"]);
gs.mc(VowelPrefixes,"put",["uw", "SG3SG3INB"]);
gs.mc(VowelPrefixes,"put",["g", "SG3SG3IN"]);
gs.mc(VowelPrefixes,"put",["h", "SG2SG3IN"]);
gs.mc(VowelPrefixes,"put",["ts", "SG2SG3INB"]);
var ConsonantPrefixes = gs.map();
gs.mc(ConsonantPrefixes,"put",["degini", "DL1INCLPL3INB"]);
gs.mc(ConsonantPrefixes,"put",["dogini", "DL1EXCLPL3INB"]);
gs.mc(ConsonantPrefixes,"put",["gegini", "PL3DL1INCL"]);
gs.mc(ConsonantPrefixes,"put",["gogini", "PL3DL1EXCL"]);
gs.mc(ConsonantPrefixes,"put",["desdi", "DL2PL3IN"]);
gs.mc(ConsonantPrefixes,"put",["detsa", "SG2PL3INB"]);
gs.mc(ConsonantPrefixes,"put",["detsi", "PL2PL3IN"]);
gs.mc(ConsonantPrefixes,"put",["dosdi", "DL1EXCLPL3IN"]);
gs.mc(ConsonantPrefixes,"put",["dotsi", "PL1EXCLPL3IN"]);
gs.mc(ConsonantPrefixes,"put",["gatsi", "SG1PL3AN"]);
gs.mc(ConsonantPrefixes,"put",["gesdi", "PL3DL2"]);
gs.mc(ConsonantPrefixes,"put",["getsi", "PL3PL2"]);
gs.mc(ConsonantPrefixes,"put",["gosdi", "DL1EXCLPL3AN"]);
gs.mc(ConsonantPrefixes,"put",["gotsi", "PL1EXCLPL3AN"]);
gs.mc(ConsonantPrefixes,"put",["ogini", "DL1EXCLSG3INB"]);
gs.mc(ConsonantPrefixes,"put",["sgini", "DL2DL1EXCL"]);
gs.mc(ConsonantPrefixes,"put",["dagi", "SG1PL3INB"]);
gs.mc(ConsonantPrefixes,"put",["dani", "PL3PL3IN"]);
gs.mc(ConsonantPrefixes,"put",["dedi", "PL1INCLPL3IN"]);
gs.mc(ConsonantPrefixes,"put",["degi", "SG3PL3IN"]);
gs.mc(ConsonantPrefixes,"put",["dehi", "SG2PL3IN"]);
gs.mc(ConsonantPrefixes,"put",["deni", "DL1INCLPL3IN"]);
gs.mc(ConsonantPrefixes,"put",["dogi", "PL1EXCLPL3INB"]);
gs.mc(ConsonantPrefixes,"put",["dugi", "PL1INCLPL3INB"]);
gs.mc(ConsonantPrefixes,"put",["duni", "PL3PL3INB"]);
gs.mc(ConsonantPrefixes,"put",["esdi", "DL2SG3AN"]);
gs.mc(ConsonantPrefixes,"put",["etsi", "PL2SG3AN"]);
gs.mc(ConsonantPrefixes,"put",["gahi", "SG2PL3AN"]);
gs.mc(ConsonantPrefixes,"put",["gedi", "PL1INCLPL3AN"]);
gs.mc(ConsonantPrefixes,"put",["gegi", "PL3PL1INCL"]);
gs.mc(ConsonantPrefixes,"put",["geni", "DL1INCLPL3AN"]);
gs.mc(ConsonantPrefixes,"put",["gini", "DL1INCLSG3INB"]);
gs.mc(ConsonantPrefixes,"put",["gogi", "PL3PL1EXCL"]);
gs.mc(ConsonantPrefixes,"put",["gvgi", "PL3SG1"]);
gs.mc(ConsonantPrefixes,"put",["isgi", "PL2DL1EXCL"]);
gs.mc(ConsonantPrefixes,"put",["itsi", "PL2SG3IN"]);
gs.mc(ConsonantPrefixes,"put",["itsv", "PL1EXCLSG2"]);
gs.mc(ConsonantPrefixes,"put",["osdi", "DL1EXCLSG3IN"]);
gs.mc(ConsonantPrefixes,"put",["otsi", "PL1EXCLSG3IN"]);
gs.mc(ConsonantPrefixes,"put",["agi", "SG1SG3INB"]);
gs.mc(ConsonantPrefixes,"put",["ani", "PL3SG3IN"]);
gs.mc(ConsonantPrefixes,"put",["edi", "PL1INCLSG3AN"]);
gs.mc(ConsonantPrefixes,"put",["eni", "DL1INCLSG3AN"]);
gs.mc(ConsonantPrefixes,"put",["idi", "PL1INCLSG3IN"]);
gs.mc(ConsonantPrefixes,"put",["igi", "PL1INCLSG3INB"]);
gs.mc(ConsonantPrefixes,"put",["ini", "DL1INCLSG3IN"]);
gs.mc(ConsonantPrefixes,"put",["ogi", "PL1EXCLSG3INB"]);
gs.mc(ConsonantPrefixes,"put",["sdi", "DL2SG3IN"]);
gs.mc(ConsonantPrefixes,"put",["sdv", "DL1EXCLDL2"]);
gs.mc(ConsonantPrefixes,"put",["sgi", "SG2SG1"]);
gs.mc(ConsonantPrefixes,"put",["tsa", "SG2SG3INB"]);
gs.mc(ConsonantPrefixes,"put",["tsi", "SG3SG2"]);
gs.mc(ConsonantPrefixes,"put",["uni", "PL3SG3INB"]);
gs.mc(ConsonantPrefixes,"put",["du", "SG3PL3INB"]);
gs.mc(ConsonantPrefixes,"put",["ga", "SG3SG3IN"]);
gs.mc(ConsonantPrefixes,"put",["gv", "SG1SG2"]);
gs.mc(ConsonantPrefixes,"put",["hi", "SG2SG3IN"]);
gs.mc(ConsonantPrefixes,"put",["u", "SG3SG3INB"]);
var InitialPrefixes = gs.map();
gs.mc(InitialPrefixes,"put",["yi", "negative"]);
gs.mc(InitialPrefixes,"put",["tsi", "relative"]);
gs.mc(InitialPrefixes,"put",["wi", "away from speaker"]);
gs.mc(InitialPrefixes,"put",["ni", "lateral position, already"]);
gs.mc(InitialPrefixes,"put",["de", "plural object"]);
gs.mc(InitialPrefixes,"put",["da", "future/motion toward speaker"]);
gs.mc(InitialPrefixes,"put",["di", "distant position"]);
gs.mc(InitialPrefixes,"put",["i", "again"]);
gs.mc(InitialPrefixes,"put",["ga", "since"]);
gs.mc(InitialPrefixes,"put",["e", "distant imperative"]);
var ReflexivePrefix = gs.map();
var PronominalPrefixes = gs.map();
gs.mc(PronominalPrefixes,"put",["SG1SG2", Prefix(gs.map().add("preVowel","gvy").add("preConsonant","gv"))]);
gs.mc(PronominalPrefixes,"put",["SG1SG3AN", Prefix(gs.map().add("preVowel","tsiy").add("preConsonant","tsi"))]);
gs.mc(PronominalPrefixes,"put",["SG1SG3IN", Prefix(gs.map().add("preVowel","g").add("preConsonant","tsi"))]);
gs.mc(PronominalPrefixes,"put",["SG1DL2", Prefix(gs.map().add("preVowel","sdvy").add("preConsonant","sdv"))]);
gs.mc(PronominalPrefixes,"put",["SG1PL2", Prefix(gs.map().add("preVowel","itsvy").add("preConsonant","itsv"))]);
gs.mc(PronominalPrefixes,"put",["SG1PL3AN", Prefix(gs.map().add("preVowel","gatsiy").add("preConsonant","gatsi"))]);
gs.mc(PronominalPrefixes,"put",["SG1PL3IN", Prefix(gs.map().add("preVowel","deg").add("preConsonant","detsi"))]);
gs.mc(PronominalPrefixes,"put",["SG2SG1", Prefix(gs.map().add("preVowel","squ").add("preConsonant","sgi"))]);
gs.mc(PronominalPrefixes,"put",["SG2SG3AN", Prefix(gs.map().add("preVowel","hiy").add("preConsonant","hi"))]);
gs.mc(PronominalPrefixes,"put",["SG2SG3IN", Prefix(gs.map().add("preVowel","h").add("preConsonant","hi"))]);
gs.mc(PronominalPrefixes,"put",["SG2DL1INCL", Prefix(gs.map().add("preVowel","sgin").add("preConsonant","sgini"))]);
gs.mc(PronominalPrefixes,"put",["SG2PL1EXCL", Prefix(gs.map().add("preVowel","isgiy").add("preConsonant","isgi"))]);
gs.mc(PronominalPrefixes,"put",["SG2PL3AN", Prefix(gs.map().add("preVowel","gahiy").add("preConsonant","gahi"))]);
gs.mc(PronominalPrefixes,"put",["SG2PL3IN", Prefix(gs.map().add("preVowel","deh").add("preConsonant","dehi"))]);
gs.mc(PronominalPrefixes,"put",["SG3SG1", Prefix(gs.map().add("preVowel","aqu").add("preConsonant","agi"))]);
gs.mc(PronominalPrefixes,"put",["SG3SG2", Prefix(gs.map().add("preVowel","ts").add("preConsonant","tsi"))]);
gs.mc(PronominalPrefixes,"put",["SG3SG3AN", Prefix(gs.map().add("preVowel","g").add("preConsonant","ga"))]);
gs.mc(PronominalPrefixes,"put",["SG3SG3IN", Prefix(gs.map().add("preVowel","g").add("preConsonant","ga"))]);
gs.mc(PronominalPrefixes,"put",["SG3DL1INCL", Prefix(gs.map().add("preVowel","gin").add("preConsonant","gini"))]);
gs.mc(PronominalPrefixes,"put",["SG3DL1EXCL", Prefix(gs.map().add("preVowel","ogin").add("preConsonant","ogini"))]);
gs.mc(PronominalPrefixes,"put",["SG3PL1INCL", Prefix(gs.map().add("preVowel","ig").add("preConsonant","igi"))]);
gs.mc(PronominalPrefixes,"put",["SG3PL1EXCL", Prefix(gs.map().add("preVowel","og").add("preConsonant","ogi"))]);
gs.mc(PronominalPrefixes,"put",["SG3DL2", Prefix(gs.map().add("preVowel","sd").add("preConsonant","sdi"))]);
gs.mc(PronominalPrefixes,"put",["SG3PL2", Prefix(gs.map().add("preVowel","its").add("preConsonant","itsi"))]);
gs.mc(PronominalPrefixes,"put",["SG3PL3AN", Prefix(gs.map().add("preVowel","deg").add("preConsonant","degi"))]);
gs.mc(PronominalPrefixes,"put",["SG3PL3IN", Prefix(gs.map().add("preVowel","deg").add("preConsonant","degi"))]);
gs.mc(PronominalPrefixes,"put",["DL1INCLSG3AN", Prefix(gs.map().add("preVowel","en").add("preConsonant","eni"))]);
gs.mc(PronominalPrefixes,"put",["DL1INCLSG3IN", Prefix(gs.map().add("preVowel","in").add("preConsonant","ini"))]);
gs.mc(PronominalPrefixes,"put",["DL1INCLPL3AN", Prefix(gs.map().add("preVowel","gen").add("preConsonant","geni"))]);
gs.mc(PronominalPrefixes,"put",["DL1INCLPL3IN", Prefix(gs.map().add("preVowel","den").add("preConsonant","deni"))]);
gs.mc(PronominalPrefixes,"put",["DL1EXCLSG2", Prefix(gs.map().add("preVowel","sdvy").add("preConsonant","sdv"))]);
gs.mc(PronominalPrefixes,"put",["DL1EXCLSG3AN", Prefix(gs.map().add("preVowel","osd").add("preConsonant","osdi"))]);
gs.mc(PronominalPrefixes,"put",["DL1EXCLSG3IN", Prefix(gs.map().add("preVowel","osd").add("preConsonant","osdi"))]);
gs.mc(PronominalPrefixes,"put",["DL1EXCLDL2", Prefix(gs.map().add("preVowel","sdvy").add("preConsonant","sdv"))]);
gs.mc(PronominalPrefixes,"put",["DL1EXCLPL2", Prefix(gs.map().add("preVowel","its").add("preConsonant","itsi"))]);
gs.mc(PronominalPrefixes,"put",["DL1EXCLPL3AN", Prefix(gs.map().add("preVowel","gosd").add("preConsonant","gosdi"))]);
gs.mc(PronominalPrefixes,"put",["DL1EXCLPL3IN", Prefix(gs.map().add("preVowel","dosd").add("preConsonant","dosdi"))]);
gs.mc(PronominalPrefixes,"put",["PL1INCLSG3AN", Prefix(gs.map().add("preVowel","ed").add("preConsonant","edi"))]);
gs.mc(PronominalPrefixes,"put",["PL1INCLSG3IN", Prefix(gs.map().add("preVowel","id").add("preConsonant","idi"))]);
gs.mc(PronominalPrefixes,"put",["PL1INCLPL3AN", Prefix(gs.map().add("preVowel","ged").add("preConsonant","gedi"))]);
gs.mc(PronominalPrefixes,"put",["PL1INCLPL3IN", Prefix(gs.map().add("preVowel","ded").add("preConsonant","dedi"))]);
gs.mc(PronominalPrefixes,"put",["PL1EXCLSG2", Prefix(gs.map().add("preVowel","itsvy").add("preConsonant","itsv"))]);
gs.mc(PronominalPrefixes,"put",["PL1EXCLSG3AN", Prefix(gs.map().add("preVowel","ots").add("preConsonant","otsi"))]);
gs.mc(PronominalPrefixes,"put",["PL1EXCLSG3IN", Prefix(gs.map().add("preVowel","ots").add("preConsonant","otsi"))]);
gs.mc(PronominalPrefixes,"put",["PL1EXCLPL3AN", Prefix(gs.map().add("preVowel","gots").add("preConsonant","gotsi"))]);
gs.mc(PronominalPrefixes,"put",["PL1EXCLPL3IN", Prefix(gs.map().add("preVowel","dots").add("preConsonant","dotsi"))]);
gs.mc(PronominalPrefixes,"put",["DL2SG1", Prefix(gs.map().add("preVowel","sgin").add("preConsonant","sgini"))]);
gs.mc(PronominalPrefixes,"put",["DL2SG3AN", Prefix(gs.map().add("preVowel","esd").add("preConsonant","esdi"))]);
gs.mc(PronominalPrefixes,"put",["DL2SG3IN", Prefix(gs.map().add("preVowel","sd").add("preConsonant","sdi"))]);
gs.mc(PronominalPrefixes,"put",["DL2DL1EXCL", Prefix(gs.map().add("preVowel","sgin").add("preConsonant","sgini"))]);
gs.mc(PronominalPrefixes,"put",["DL2PL1EXCL", Prefix(gs.map().add("preVowel","isgiy").add("preConsonant","isgi"))]);
gs.mc(PronominalPrefixes,"put",["DL2PL3AN", Prefix(gs.map().add("preVowel","gesd").add("preConsonant","gesdi"))]);
gs.mc(PronominalPrefixes,"put",["DL2PL3IN", Prefix(gs.map().add("preVowel","desd").add("preConsonant","desdi"))]);
gs.mc(PronominalPrefixes,"put",["PL2SG1", Prefix(gs.map().add("preVowel","isgiy").add("preConsonant","isgi"))]);
gs.mc(PronominalPrefixes,"put",["PL2SG3AN", Prefix(gs.map().add("preVowel","ets").add("preConsonant","etsi"))]);
gs.mc(PronominalPrefixes,"put",["PL2SG3IN", Prefix(gs.map().add("preVowel","its").add("preConsonant","itsi"))]);
gs.mc(PronominalPrefixes,"put",["PL2DL1EXCL", Prefix(gs.map().add("preVowel","isgiy").add("preConsonant","isgi"))]);
gs.mc(PronominalPrefixes,"put",["PL2PL3AN", Prefix(gs.map().add("preVowel","gets").add("preConsonant","getsi"))]);
gs.mc(PronominalPrefixes,"put",["PL2PL3IN", Prefix(gs.map().add("preVowel","dets").add("preConsonant","detsi"))]);
gs.mc(PronominalPrefixes,"put",["PL3SG1", Prefix(gs.map().add("preVowel","gvqu").add("preConsonant","gvgi"))]);
gs.mc(PronominalPrefixes,"put",["PL3SG2", Prefix(gs.map().add("preVowel","gets").add("preConsonant","getsi"))]);
gs.mc(PronominalPrefixes,"put",["PL3SG3AN", Prefix(gs.map().add("preVowel","an").add("preConsonant","ani"))]);
gs.mc(PronominalPrefixes,"put",["PL3SG3IN", Prefix(gs.map().add("preVowel","an").add("preConsonant","ani"))]);
gs.mc(PronominalPrefixes,"put",["PL3DL1INCL", Prefix(gs.map().add("preVowel","gegin").add("preConsonant","gegini"))]);
gs.mc(PronominalPrefixes,"put",["PL3DL1EXCL", Prefix(gs.map().add("preVowel","gogin").add("preConsonant","gogini"))]);
gs.mc(PronominalPrefixes,"put",["PL3PL1INCL", Prefix(gs.map().add("preVowel","geg").add("preConsonant","gegi"))]);
gs.mc(PronominalPrefixes,"put",["PL3PL1EXCL", Prefix(gs.map().add("preVowel","gog").add("preConsonant","gogi"))]);
gs.mc(PronominalPrefixes,"put",["PL3DL2", Prefix(gs.map().add("preVowel","gesd").add("preConsonant","gesdi"))]);
gs.mc(PronominalPrefixes,"put",["PL3PL2", Prefix(gs.map().add("preVowel","gets").add("preConsonant","getsi"))]);
gs.mc(PronominalPrefixes,"put",["PL3PL3AN", Prefix(gs.map().add("preVowel","dan").add("preConsonant","dani"))]);
gs.mc(PronominalPrefixes,"put",["PL3PL3IN", Prefix(gs.map().add("preVowel","dan").add("preConsonant","dani"))]);
gs.mc(PronominalPrefixes,"put",["SG1SG3INB", Prefix(gs.map().add("preVowel","aqu").add("preConsonant","agi"))]);
gs.mc(PronominalPrefixes,"put",["SG2SG3INB", Prefix(gs.map().add("preVowel","ts").add("preConsonant","tsa"))]);
gs.mc(PronominalPrefixes,"put",["SG3SG3INB", Prefix(gs.map().add("preVowel","uw").add("preConsonant","u"))]);
gs.mc(PronominalPrefixes,"put",["DL1INCLSG3INB", Prefix(gs.map().add("preVowel","gin").add("preConsonant","gini"))]);
gs.mc(PronominalPrefixes,"put",["PL1INCLSG3INB", Prefix(gs.map().add("preVowel","ig").add("preConsonant","igi"))]);
gs.mc(PronominalPrefixes,"put",["DL1EXCLSG3INB", Prefix(gs.map().add("preVowel","ogin").add("preConsonant","ogini"))]);
gs.mc(PronominalPrefixes,"put",["PL1EXCLSG3INB", Prefix(gs.map().add("preVowel","og").add("preConsonant","ogi"))]);
gs.mc(PronominalPrefixes,"put",["PL3SG3INB", Prefix(gs.map().add("preVowel","un").add("preConsonant","uni"))]);
gs.mc(PronominalPrefixes,"put",["SG1PL3INB", Prefix(gs.map().add("preVowel","daqu").add("preConsonant","dagi"))]);
gs.mc(PronominalPrefixes,"put",["SG2PL3INB", Prefix(gs.map().add("preVowel","duts").add("preConsonant","detsa"))]);
gs.mc(PronominalPrefixes,"put",["SG3PL3INB", Prefix(gs.map().add("preVowel","duw").add("preConsonant","du"))]);
gs.mc(PronominalPrefixes,"put",["DL1INCLPL3INB", Prefix(gs.map().add("preVowel","dugin").add("preConsonant","degini"))]);
gs.mc(PronominalPrefixes,"put",["PL1INCLPL3INB", Prefix(gs.map().add("preVowel","dug").add("preConsonant","dugi"))]);
gs.mc(PronominalPrefixes,"put",["DL1EXCLPL3INB", Prefix(gs.map().add("preVowel","dogin").add("preConsonant","dogini"))]);
gs.mc(PronominalPrefixes,"put",["PL1EXCLPL3INB", Prefix(gs.map().add("preVowel","dog").add("preConsonant","dogi"))]);
gs.mc(PronominalPrefixes,"put",["PL3PL3INB", Prefix(gs.map().add("preVowel","dun").add("preConsonant","duni"))]);
