enum Tense {
    PRESENT,
    FUTURE_IMPERATIVE,
    INFINITIVE,
    HABITUAL,
    PLUPERFECT,
    FUTURE_PROGRESSIVE,
    REPORTATIVE,
    PAST,
    FUTURE,
    PRE_INCIPIENT
}

def VerbTense = [:]
VerbTense.put("esdi" , Tense.FUTURE_PROGRESSIVE)
VerbTense.put("idi" , Tense.PRE_INCIPIENT)
VerbTense.put("vi" , Tense.FUTURE_IMPERATIVE)
// VerbTense.put("a" , Tense.PRESENT)
VerbTense.put("di" , Tense.INFINITIVE)
VerbTense.put("oi" , Tense.HABITUAL)
VerbTense.put("oi" , Tense.PLUPERFECT)
// VerbTense.put("esdi" , Tense.FUTURE_PROGRESSIVE)
VerbTense.put("ei" , Tense.REPORTATIVE)
VerbTense.put("vi" , Tense.PAST)
VerbTense.put("i" , Tense.FUTURE)
VerbTense.put("a" , Tense.PRESENT)
// VerbTense.put("idi" , Tense.PRE_INCIPIENT)

def VerbTenseLookup = [:]
VerbTenseLookup.put("FUTURE_PROGRESSIVE",  "esdi")
VerbTenseLookup.put("PRE_INCIPIENT",  "idi")
VerbTenseLookup.put("FUTURE_IMPERATIVE",  "vi")
// VerbTenseLookup.put("a" ",  "PRESENT, )
VerbTenseLookup.put("INFINITIVE",  "di")
VerbTenseLookup.put("HABITUAL",  "oi")
VerbTenseLookup.put("PLUPERFECT",  "oi")
// VerbTenseLookup.put("esdi" ",  "FUTURE_PROGRESSIVE, )
VerbTenseLookup.put("REPORTATIVE",  "ei")
VerbTenseLookup.put("PAST",  "vi")
VerbTenseLookup.put("FUTURE",  "i")
VerbTenseLookup.put("PRESENT",  "a")

def FinalEndings = [:]
FinalEndings.put("dv", "focus")
FinalEndings.put("dina", "concessiveImperative")
FinalEndings.put("isi", "orelse")
FinalEndings.put("hv", "but")
FinalEndings.put("na", "andWhatIf")
FinalEndings.put("ke", "orInterrogative")
FinalEndings.put("tsu", "interrogative")
FinalEndings.put("sgo", "interrogative2")
FinalEndings.put("gwu", "onlyJustStill")
FinalEndings.put("quu", "onlyJustStill")

def NonFinalEndings = [:]
NonFinalEndings.put("dohdan", "unintentional")
NonFinalEndings.put("idol", "around")
NonFinalEndings.put("ilo", "repetitive")
NonFinalEndings.put("ilos", "repetitive")
NonFinalEndings.put("ilots", "repetitive")
NonFinalEndings.put("ihl", "comeTo")
NonFinalEndings.put("dan", "instrumentalCausative")
NonFinalEndings.put("ohn", "completive")
NonFinalEndings.put("is", "duplicative/become")
NonFinalEndings.put("el", "dativeBenefactive")
NonFinalEndings.put("gi", "reversive")
NonFinalEndings.put("g", "progressive")
NonFinalEndings.put("e", "atIntervals")
NonFinalEndings.put("y", "reversive")
NonFinalEndings.put("e", "reversive")
// NonFinalEndings.put("g", "progressive")
// NonFinalEndings.put("ihl", "comeTo")
// NonFinalEndings.put("e", "atIntervals")
// NonFinalEndings.put("idol", "around")
// NonFinalEndings.put("el", "dativeBenefactive")
// NonFinalEndings.put("ohn", "completive")
// NonFinalEndings.put("dohdan", "unintentional")
// NonFinalEndings.put("dan", "instrumentalCausative")
// NonFinalEndings.put("ilo", "repetitive")
// NonFinalEndings.put("is", "duplicative/become")
// NonFinalEndings.put("y", "reversive")
// NonFinalEndings.put("e", "reversive")
// NonFinalEndings.put("gi", "reversive")

//verbTense = Tense.PRESENT

// phonetic = value of item in explanation
// syllabary = syllabic representation if available
// type = suffix, prefix, root, non-final suffix, final suffix, initial prefix, proniminal prefix, reflexive prefix
// function = pronoun, like focus,
// meaning = focus etc
//function createExplanation(phonetic, syllabary, type, purpose, meaning, name) {
//    var explanation = {
//        phonetic: phonetic,
//        syllabary: syllabary,
//        meaning: meaning,
//        purpose: purpose,
//        name: name
//        // morpheme_romanized: "d",
//        // morpheme_syllabary: "XX",
//        // morpheme_name: "prefix",
//        // morpheme_function: "plurality",
//        // morpheme_meaning: "many",
//    }
//
//    return explanation
//}

def VowelPrefixes = [:]
VowelPrefixes.put("gatsiy", "SG1PL3AN")
VowelPrefixes.put("dogin", "DL1EXCLPL3INB")
VowelPrefixes.put("dugin", "DL1INCLPL3INB")
VowelPrefixes.put("gahiy", "SG2PL3AN")
VowelPrefixes.put("gegin", "PL3DL1INCL")
VowelPrefixes.put("gogin", "PL3DL1EXCL")
VowelPrefixes.put("isgiy", "PL2DL1EXCL")
VowelPrefixes.put("itsvy", "PL1EXCLSG2")
VowelPrefixes.put("daqu", "SG1PL3INB")
VowelPrefixes.put("dagw", "SG1PL3INB")
VowelPrefixes.put("desd", "DL2PL3IN")
VowelPrefixes.put("dosd", "DL1EXCLPL3IN")
VowelPrefixes.put("gesd", "PL3DL2")
VowelPrefixes.put("gosd", "DL1EXCLPL3AN")
VowelPrefixes.put("gvqu", "PL3SG1")
VowelPrefixes.put("gvgw", "PL3SG1")
VowelPrefixes.put("ogin", "DL1EXCLSG3INB")
VowelPrefixes.put("sdvy", "DL1EXCLDL2")
VowelPrefixes.put("sgin", "DL2DL1EXCL")
VowelPrefixes.put("tsiy", "SG1SG3AN")
VowelPrefixes.put("aqu", "SG1SG3INB")
VowelPrefixes.put("agw", "SG1SG3INB")
VowelPrefixes.put("dan", "PL3PL3IN")
VowelPrefixes.put("ded", "PL1INCLPL3IN")
VowelPrefixes.put("deg", "SG3PL3IN")
VowelPrefixes.put("deh", "SG2PL3IN")
VowelPrefixes.put("dets", "PL2PL3IN")
VowelPrefixes.put("den", "DL1INCLPL3IN")
VowelPrefixes.put("dog", "PL1EXCLPL3INB")
VowelPrefixes.put("dots", "PL1EXCLPL3IN")
VowelPrefixes.put("dug", "PL1INCLPL3INB")
VowelPrefixes.put("duts", "SG2PL3INB")
VowelPrefixes.put("dun", "PL3PL3INB")
VowelPrefixes.put("duw", "SG3PL3INB")
VowelPrefixes.put("esd", "DL2SG3AN")
VowelPrefixes.put("ged", "PL1INCLPL3AN")
VowelPrefixes.put("geg", "PL3PL1INCL")
VowelPrefixes.put("gets", "PL3PL2")
VowelPrefixes.put("gen", "DL1INCLPL3AN")
VowelPrefixes.put("gin", "DL1INCLSG3INB")
VowelPrefixes.put("gog", "PL3PL1EXCL")
VowelPrefixes.put("gots", "PL1EXCLPL3AN")
VowelPrefixes.put("gvy", "SG1SG2")
VowelPrefixes.put("hiy", "SG2SG3AN")
VowelPrefixes.put("osd", "DL1EXCLSG3IN")
VowelPrefixes.put("squ", "SG2SG1")
VowelPrefixes.put("sgw", "SG2SG1")
VowelPrefixes.put("an", "PL3SG3IN")
VowelPrefixes.put("ed", "PL1INCLSG3AN")
VowelPrefixes.put("ets", "PL2SG3AN")
VowelPrefixes.put("en", "DL1INCLSG3AN")
VowelPrefixes.put("id", "PL1INCLSG3IN")
VowelPrefixes.put("ig", "PL1INCLSG3INB")
VowelPrefixes.put("its", "PL2SG3IN")
VowelPrefixes.put("in", "DL1INCLSG3IN")
VowelPrefixes.put("og", "PL1EXCLSG3INB")
VowelPrefixes.put("ots", "PL1EXCLSG3IN")
VowelPrefixes.put("sd", "DL2SG3IN")
VowelPrefixes.put("un", "PL3SG3INB")
VowelPrefixes.put("uw", "SG3SG3INB")
VowelPrefixes.put("g", "SG3SG3IN")
VowelPrefixes.put("h", "SG2SG3IN")
VowelPrefixes.put("ts", "SG2SG3INB")

def ConsonantPrefixes = [:]
ConsonantPrefixes.put("degini", "DL1INCLPL3INB")
ConsonantPrefixes.put("dogini", "DL1EXCLPL3INB")
ConsonantPrefixes.put("gegini", "PL3DL1INCL")
ConsonantPrefixes.put("gogini", "PL3DL1EXCL")
ConsonantPrefixes.put("desdi", "DL2PL3IN")
ConsonantPrefixes.put("detsa", "SG2PL3INB")
ConsonantPrefixes.put("detsi", "PL2PL3IN")
ConsonantPrefixes.put("dosdi", "DL1EXCLPL3IN")
ConsonantPrefixes.put("dotsi", "PL1EXCLPL3IN")
ConsonantPrefixes.put("gatsi", "SG1PL3AN")
ConsonantPrefixes.put("gesdi", "PL3DL2")
ConsonantPrefixes.put("getsi", "PL3PL2")
ConsonantPrefixes.put("gosdi", "DL1EXCLPL3AN")
ConsonantPrefixes.put("gotsi", "PL1EXCLPL3AN")
ConsonantPrefixes.put("ogini", "DL1EXCLSG3INB")
ConsonantPrefixes.put("sgini", "DL2DL1EXCL")
ConsonantPrefixes.put("dagi", "SG1PL3INB")
ConsonantPrefixes.put("dani", "PL3PL3IN")
ConsonantPrefixes.put("dedi", "PL1INCLPL3IN")
ConsonantPrefixes.put("degi", "SG3PL3IN")
ConsonantPrefixes.put("dehi", "SG2PL3IN")
ConsonantPrefixes.put("deni", "DL1INCLPL3IN")
ConsonantPrefixes.put("dogi", "PL1EXCLPL3INB")
ConsonantPrefixes.put("dugi", "PL1INCLPL3INB")
ConsonantPrefixes.put("duni", "PL3PL3INB")
ConsonantPrefixes.put("esdi", "DL2SG3AN")
ConsonantPrefixes.put("etsi", "PL2SG3AN")
ConsonantPrefixes.put("gahi", "SG2PL3AN")
ConsonantPrefixes.put("gedi", "PL1INCLPL3AN")
ConsonantPrefixes.put("gegi", "PL3PL1INCL")
ConsonantPrefixes.put("geni", "DL1INCLPL3AN")
ConsonantPrefixes.put("gini", "DL1INCLSG3INB")
ConsonantPrefixes.put("gogi", "PL3PL1EXCL")
ConsonantPrefixes.put("gvgi", "PL3SG1")
ConsonantPrefixes.put("isgi", "PL2DL1EXCL")
ConsonantPrefixes.put("itsi", "PL2SG3IN")
ConsonantPrefixes.put("itsv", "PL1EXCLSG2")
ConsonantPrefixes.put("osdi", "DL1EXCLSG3IN")
ConsonantPrefixes.put("otsi", "PL1EXCLSG3IN")
ConsonantPrefixes.put("agi", "SG1SG3INB")
ConsonantPrefixes.put("ani", "PL3SG3IN")
ConsonantPrefixes.put("edi", "PL1INCLSG3AN")
ConsonantPrefixes.put("eni", "DL1INCLSG3AN")
ConsonantPrefixes.put("idi", "PL1INCLSG3IN")
ConsonantPrefixes.put("igi", "PL1INCLSG3INB")
ConsonantPrefixes.put("ini", "DL1INCLSG3IN")
ConsonantPrefixes.put("ogi", "PL1EXCLSG3INB")
ConsonantPrefixes.put("sdi", "DL2SG3IN")
ConsonantPrefixes.put("sdv", "DL1EXCLDL2")
ConsonantPrefixes.put("sgi", "SG2SG1")
ConsonantPrefixes.put("tsa", "SG2SG3INB")
ConsonantPrefixes.put("tsi", "SG3SG2")
ConsonantPrefixes.put("uni", "PL3SG3INB")
ConsonantPrefixes.put("du", "SG3PL3INB")
ConsonantPrefixes.put("ga", "SG3SG3IN")
ConsonantPrefixes.put("gv", "SG1SG2")
ConsonantPrefixes.put("hi", "SG2SG3IN")
ConsonantPrefixes.put("u", "SG3SG3INB")

def InitialPrefixes = [:]
InitialPrefixes.put("yi", "negative")
InitialPrefixes.put("tsi", "relative")
InitialPrefixes.put("wi", "away from speaker")
InitialPrefixes.put("ni", "lateral position, already")
InitialPrefixes.put("de", "plural object")
InitialPrefixes.put("da", "future/motion toward speaker")
InitialPrefixes.put("di", "distant position")
InitialPrefixes.put("i", "again")
InitialPrefixes.put("ga", "since")
InitialPrefixes.put("e", "distant imperative")

def ReflexivePrefix = [:]

def PronominalPrefixes = [:]
PronominalPrefixes.put('SG1SG2', new Prefix(preVowel:'gvy', preConsonant:'gv'))
PronominalPrefixes.put('SG1SG3AN', new Prefix(preVowel:'tsiy', preConsonant:'tsi'))
PronominalPrefixes.put('SG1SG3IN', new Prefix(preVowel:'g', preConsonant:'tsi'))
PronominalPrefixes.put('SG1DL2', new Prefix(preVowel:'sdvy', preConsonant:'sdv'))
PronominalPrefixes.put('SG1PL2', new Prefix(preVowel:'itsvy', preConsonant:'itsv'))
PronominalPrefixes.put('SG1PL3AN', new Prefix(preVowel:'gatsiy', preConsonant:'gatsi'))
PronominalPrefixes.put('SG1PL3IN', new Prefix(preVowel:'deg', preConsonant:'detsi'))
PronominalPrefixes.put('SG2SG1', new Prefix(preVowel:'squ', preConsonant:'sgi'))
PronominalPrefixes.put('SG2SG3AN', new Prefix(preVowel:'hiy', preConsonant:'hi'))
PronominalPrefixes.put('SG2SG3IN', new Prefix(preVowel:'h', preConsonant:'hi'))
PronominalPrefixes.put('SG2DL1INCL', new Prefix(preVowel:'sgin', preConsonant:'sgini'))
PronominalPrefixes.put('SG2PL1EXCL', new Prefix(preVowel:'isgiy', preConsonant:'isgi'))
PronominalPrefixes.put('SG2PL3AN', new Prefix(preVowel:'gahiy', preConsonant:'gahi'))
PronominalPrefixes.put('SG2PL3IN', new Prefix(preVowel:'deh', preConsonant:'dehi'))
PronominalPrefixes.put('SG3SG1', new Prefix(preVowel:'aqu', preConsonant:'agi'))
PronominalPrefixes.put('SG3SG2', new Prefix(preVowel:'ts', preConsonant:'tsi'))
PronominalPrefixes.put('SG3SG3AN', new Prefix(preVowel:'g', preConsonant:'ga'))
PronominalPrefixes.put('SG3SG3IN', new Prefix(preVowel:'g', preConsonant:'ga'))
PronominalPrefixes.put('SG3DL1INCL', new Prefix(preVowel:'gin', preConsonant:'gini'))
PronominalPrefixes.put('SG3DL1EXCL', new Prefix(preVowel:'ogin', preConsonant:'ogini'))
PronominalPrefixes.put('SG3PL1INCL', new Prefix(preVowel:'ig', preConsonant:'igi'))
PronominalPrefixes.put('SG3PL1EXCL', new Prefix(preVowel:'og', preConsonant:'ogi'))
PronominalPrefixes.put('SG3DL2', new Prefix(preVowel:'sd', preConsonant:'sdi'))
PronominalPrefixes.put('SG3PL2', new Prefix(preVowel:'its', preConsonant:'itsi'))
PronominalPrefixes.put('SG3PL3AN', new Prefix(preVowel:'deg', preConsonant:'degi'))
PronominalPrefixes.put('SG3PL3IN', new Prefix(preVowel:'deg', preConsonant:'degi'))
PronominalPrefixes.put('DL1INCLSG3AN', new Prefix(preVowel:'en', preConsonant:'eni'))
PronominalPrefixes.put('DL1INCLSG3IN', new Prefix(preVowel:'in', preConsonant:'ini'))
PronominalPrefixes.put('DL1INCLPL3AN', new Prefix(preVowel:'gen', preConsonant:'geni'))
PronominalPrefixes.put('DL1INCLPL3IN', new Prefix(preVowel:'den', preConsonant:'deni'))
PronominalPrefixes.put('DL1EXCLSG2', new Prefix(preVowel:'sdvy', preConsonant:'sdv'))
PronominalPrefixes.put('DL1EXCLSG3AN', new Prefix(preVowel:'osd', preConsonant:'osdi'))
PronominalPrefixes.put('DL1EXCLSG3IN', new Prefix(preVowel:'osd', preConsonant:'osdi'))
PronominalPrefixes.put('DL1EXCLDL2', new Prefix(preVowel:'sdvy', preConsonant:'sdv'))
PronominalPrefixes.put('DL1EXCLPL2', new Prefix(preVowel:'its', preConsonant:'itsi'))
PronominalPrefixes.put('DL1EXCLPL3AN', new Prefix(preVowel:'gosd', preConsonant:'gosdi'))
PronominalPrefixes.put('DL1EXCLPL3IN', new Prefix(preVowel:'dosd', preConsonant:'dosdi'))
PronominalPrefixes.put('PL1INCLSG3AN', new Prefix(preVowel:'ed', preConsonant:'edi'))
PronominalPrefixes.put('PL1INCLSG3IN', new Prefix(preVowel:'id', preConsonant:'idi'))
PronominalPrefixes.put('PL1INCLPL3AN', new Prefix(preVowel:'ged', preConsonant:'gedi'))
PronominalPrefixes.put('PL1INCLPL3IN', new Prefix(preVowel:'ded', preConsonant:'dedi'))
PronominalPrefixes.put('PL1EXCLSG2', new Prefix(preVowel:'itsvy', preConsonant:'itsv'))
PronominalPrefixes.put('PL1EXCLSG3AN', new Prefix(preVowel:'ots', preConsonant:'otsi'))
PronominalPrefixes.put('PL1EXCLSG3IN', new Prefix(preVowel:'ots', preConsonant:'otsi'))
PronominalPrefixes.put('PL1EXCLPL3AN', new Prefix(preVowel:'gots', preConsonant:'gotsi'))
PronominalPrefixes.put('PL1EXCLPL3IN', new Prefix(preVowel:'dots', preConsonant:'dotsi'))
PronominalPrefixes.put('DL2SG1', new Prefix(preVowel:'sgin', preConsonant:'sgini'))
PronominalPrefixes.put('DL2SG3AN', new Prefix(preVowel:'esd', preConsonant:'esdi'))
PronominalPrefixes.put('DL2SG3IN', new Prefix(preVowel:'sd', preConsonant:'sdi'))
PronominalPrefixes.put('DL2DL1EXCL', new Prefix(preVowel:'sgin', preConsonant:'sgini'))
PronominalPrefixes.put('DL2PL1EXCL', new Prefix(preVowel:'isgiy', preConsonant:'isgi'))
PronominalPrefixes.put('DL2PL3AN', new Prefix(preVowel:'gesd', preConsonant:'gesdi'))
PronominalPrefixes.put('DL2PL3IN', new Prefix(preVowel:'desd', preConsonant:'desdi'))
PronominalPrefixes.put('PL2SG1', new Prefix(preVowel:'isgiy', preConsonant:'isgi'))
PronominalPrefixes.put('PL2SG3AN', new Prefix(preVowel:'ets', preConsonant:'etsi'))
PronominalPrefixes.put('PL2SG3IN', new Prefix(preVowel:'its', preConsonant:'itsi'))
PronominalPrefixes.put('PL2DL1EXCL', new Prefix(preVowel:'isgiy', preConsonant:'isgi'))
PronominalPrefixes.put('PL2PL3AN', new Prefix(preVowel:'gets', preConsonant:'getsi'))
PronominalPrefixes.put('PL2PL3IN', new Prefix(preVowel:'dets', preConsonant:'detsi'))
PronominalPrefixes.put('PL3SG1', new Prefix(preVowel:'gvqu', preConsonant:'gvgi'))
PronominalPrefixes.put('PL3SG2', new Prefix(preVowel:'gets', preConsonant:'getsi'))
PronominalPrefixes.put('PL3SG3AN', new Prefix(preVowel:'an', preConsonant:'ani'))
PronominalPrefixes.put('PL3SG3IN', new Prefix(preVowel:'an', preConsonant:'ani'))
PronominalPrefixes.put('PL3DL1INCL', new Prefix(preVowel:'gegin', preConsonant:'gegini'))
PronominalPrefixes.put('PL3DL1EXCL', new Prefix(preVowel:'gogin', preConsonant:'gogini'))
PronominalPrefixes.put('PL3PL1INCL', new Prefix(preVowel:'geg', preConsonant:'gegi'))
PronominalPrefixes.put('PL3PL1EXCL', new Prefix(preVowel:'gog', preConsonant:'gogi'))
PronominalPrefixes.put('PL3DL2', new Prefix(preVowel:'gesd', preConsonant:'gesdi'))
PronominalPrefixes.put('PL3PL2', new Prefix(preVowel:'gets', preConsonant:'getsi'))
PronominalPrefixes.put('PL3PL3AN', new Prefix(preVowel:'dan', preConsonant:'dani'))
PronominalPrefixes.put('PL3PL3IN', new Prefix(preVowel:'dan', preConsonant:'dani'))
PronominalPrefixes.put('SG1SG3INB', new Prefix(preVowel:'aqu', preConsonant:'agi'))
PronominalPrefixes.put('SG2SG3INB', new Prefix(preVowel:'ts', preConsonant:'tsa'))
PronominalPrefixes.put('SG3SG3INB', new Prefix(preVowel:'uw', preConsonant:'u'))
PronominalPrefixes.put('DL1INCLSG3INB', new Prefix(preVowel:'gin', preConsonant:'gini'))
PronominalPrefixes.put('PL1INCLSG3INB', new Prefix(preVowel:'ig', preConsonant:'igi'))
PronominalPrefixes.put('DL1EXCLSG3INB', new Prefix(preVowel:'ogin', preConsonant:'ogini'))
PronominalPrefixes.put('PL1EXCLSG3INB', new Prefix(preVowel:'og', preConsonant:'ogi'))
PronominalPrefixes.put('PL3SG3INB', new Prefix(preVowel:'un', preConsonant:'uni'))
PronominalPrefixes.put('SG1PL3INB', new Prefix(preVowel:'daqu', preConsonant:'dagi'))
PronominalPrefixes.put('SG2PL3INB', new Prefix(preVowel:'duts', preConsonant:'detsa'))
PronominalPrefixes.put('SG3PL3INB', new Prefix(preVowel:'duw', preConsonant:'du'))
PronominalPrefixes.put('DL1INCLPL3INB', new Prefix(preVowel:'dugin', preConsonant:'degini'))
PronominalPrefixes.put('PL1INCLPL3INB', new Prefix(preVowel:'dug', preConsonant:'dugi'))
PronominalPrefixes.put('DL1EXCLPL3INB', new Prefix(preVowel:'dogin', preConsonant:'dogini'))
PronominalPrefixes.put('PL1EXCLPL3INB', new Prefix(preVowel:'dog', preConsonant:'dogi'))
PronominalPrefixes.put('PL3PL3INB', new Prefix(preVowel:'dun', preConsonant:'duni'))

class Prefix {
    def preVowel
    def preConsonant
}